name: indigo-tulip-db

services:
  db:
    image: postgres:18-alpine
    container_name: indigo-db-container
    restart: always
    env_file:
      - ./apps/server/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: app_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql 

volumes:
  pgdata:
    name: indigo_tulip_pgdata